spring:
  application:
    name: railway-stats
  profiles:
    active: dev

vaadin:
  launch-browser: true
  production-mode: false

tripinfo:
  scheduling:
    prune-cron: "0 40 23 * * ?"
    collect-cron: "59 50 23 * * ?"
    zone: "Europe/Stockholm"
  retention:
    days: 30

